export const AuthErrors = {
  USER_VERIFICATION_FAILED: 'Error verifying user',
  INVALID_ROLE: 'Invalid role',
  USER_CREATION_FAILED: 'User creation failed',
  USER_NOT_FOUND: 'User not found',
  JWT_SECRET_UNDEFINED: 'JWT secret is not defined',
  JWT_TOKEN_EXPIRED: 'JWT Token Expired',
  ENV_VARIABLE_UNDEFINED: 'is not defined in the environment variables',
  PASSWORD_COMPARISON_FAILED: 'Password comparison failed',
  VERIFICATION_FAILED: 'Verification failed',
  DISABLE_FAILED: '2FA Disable Failed',
  SIGNUP_FAILED: 'Signup Failed',
  INVALID_2FA_SETUP: 'Invalid two-factor authentication setup',
  MISSING_2FA_TOKEN: 'Two-factor authentication token is missing',
  INVALID_2FA_TOKEN: 'Invalid two-factor authentication token',
  USER_UNAUTHORIZED: 'User is Unauthorized',
  FAILED_GENERATE_URL: 'Failed to generate OTP authentication URL',
  FRONTEND_FORGOT_PASSWORD_LINK_NOT_FOUND:
    'Frontend Forgot Password Link Not Found',
  INVALID_TOKEN: 'Token is Invalid',
  TOKEN_NOT_GENERATED_FOR_MAIL : 'Token Not Generated For Sending with Mail',
  INVALID_PASSWORD : "Username Or Password Invalid",
  USER_ALREADY_EXISTS_BUT_UNAUTHORIZED : 'User already Exists but Unauthorized',
} as const;
